<?php 
 return array (
  'BASE_INFO_EMAIL' => 'help@admin.com',
  'BASE_INFO_TELPHONE' => '0755-8888888',
  'BASE_INFO_MOBILE' => '13800138000',
  'BASE_INFO_ADDRESS' => '深圳南山马花路213号',
  'DATA_BACKUP_PATH' => './Data/',
  'DATA_BACKUP_PART_SIZE' => '20971520',
  'DATA_BACKUP_COMPRESS' => '0',
  'DATA_BACKUP_COMPRESS_LEVEL' => '1',
  'SWITCH_PRODUCT_FREE' => '1',
  'SWITCH_COUPON_USE' => '1',
  'NUM_BUILD_INVITE' => '1',
  'NUM_BUILD_COUPON' => '1',
  'COUPON_EXPIRE' => '2592000',
  'COUPON_RAND_TYPE' => '0',
  'COUPON_REBUILD' => 604800,
  'ORDER_EXPIRE' => '3600',
  'SHOW_PAGE_TRACE' => '0',
  'WEB_SITE_CLOSE' => '1',
  'USER_ALLOW_REGISTER' => '1',
)
 ?>